name: Build and deploy

on:
  push:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew build

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u kulturman --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/kulturman/mdd-backend:${{ github.sha }} .
          docker build -t ghcr.io/kulturman/mdd-backend:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/kulturman/mdd-backend:${{ github.sha }}
          docker push ghcr.io/kulturman/mdd-backend:latest

      - name: Copy docker-compose file to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          source: docker-compose-deploy.yml
          target: /home/${{ secrets.REMOTE_USER }}/mdd

      - name: Deploy to dev environment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          script: |
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u gump-ci --password-stdin
            cd mdd
            echo COMMIT_SHA=${{ github.sha }} > .env
            docker-compose -f docker-compose-deploy.yml up -d

