name: Build and deploy

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew build

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u kulturman --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/kulturman/mdd-backend-${{ github.sha }} .

      - name: Push Docker image
        run: docker push ghcr.io/kulturman/mdd-backend-${{ github.sha }}
